name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Newman and HTML Extra Reporter
      run: npm install newman newman-reporter-htmlextra

    - name: Fetch Postman Environment
      run: |
        echo "Attempting to fetch environment with ID: d7e1bfa4-5b18-44e6-982b-5834b6f78241"
        curl -X GET "https://api.getpostman.com/environments/d7e1bfa4-5b18-44e6-982b-5834b6f78241" \
          -H "X-Api-Key: $POSTMAN_API_KEY" \
          -o environment.json || { echo "Error: Curl command failed. Ensure your Postman API Key is correct."; exit 1; }
        echo "Environment file fetched to environment.json."

    - name: Transform Environment File
      run: |
        if ! jq '.environment' environment.json > environment_transformed.json; then
          echo "Error: jq transformation failed. Ensure jq is installed and the environment file is valid."; 
          exit 1; 
        fi
        echo "Environment file transformed successfully."

    - name: Debug - Show Environment Files
      run: |
        echo "Original environment.json content:"
        cat environment.json
        echo "Transformed environment_transformed.json content:"
        cat environment_transformed.json

    - name: Run API tests with Newman and generate HTMLExtra report (Negative Scenarios)
      run: |
        echo "Running Negative API Tests..."
        npx newman run "${{ github.workspace }}/postman/collections/NASA_Negative_Tests.json" \
          -e environment_transformed.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export newman-report-negative.html || { echo "Newman Negative Test Run failed."; exit 1; }

    - name: Run API tests with Newman and generate HTMLExtra report (Positive Scenarios)
      run: |
        echo "Running Positive API Tests..."
        npx newman run "${{ github.workspace }}/postman/collections/NASA_Positive_Tests.json" \
          -e environment_transformed.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export newman-report-positive.html || { echo "Newman Positive Test Run failed."; exit 1; }

    - name: Upload Negative HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report-negative
        path: newman-report-negative.html
        retention-days: 7

    - name: Upload Positive HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report-positive
        path: newman-report-positive.html
        retention-days: 7
